server:
  port: 8764

spring:
  application:
    name: auth-service
  datasource:
    username: dunglt
    password: dunglt@123
    url: jdbc:postgresql://localhost:5432/iks-users
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
  config:
    import:
    - optional:configserver:http://localhost:8762            
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400